### ISSUE TITLE
Problem with Ui

### ISSUE THREAD

**Issue by Najkelo** [stackpoint/anbennar_tweaks#2]
Please, could you tell me how to play this mod with resolution lower that ...x1080? What files do i need to edit? Sorry for the trouble but i would love to play this mod with my friends.

**Comment by stackpoint** [comment]
@afowl which interface files should he delete to get this working?

**Comment by ghost** [comment]
Hi! im not an expert, by all means. My game used to crash until i started using windowed mode (instead of fulscreen). UI is wacky in my 1440x900 monitor, but at least it let's me play! Hope it helps OP :)

**Comment by stackpoint** [comment]
For future reference: 

![image](https://user-images.githubusercontent.com/5704491/111043502-05079880-83e7-11eb-9e34-237616063600.png)
