### ISSUE TITLE
Auto-Development bug - 129 dev in every province

### ISSUE THREAD

**Issue by ghost** [stackpoint/anbennar_tweaks#5]
When at mana cap with auto-dev on, whether it be player or AI, the mana isn't actually spent when the province is developed. If the AI or player sits at mana point cap with auto-dev on, then their provinces will develop for free every month. This only stops when a province hits 129 development, after which you lose about 40-50 mana.
This can be demonstrated by starting as a small country, giving yourself 999 mana and turning on auto-dev. Each month, your lowest dev cost province will get 1 development from whatever mana you're at cap with, without actually spending any.

**Comment by stackpoint** [comment]
It looks like base anbennar imported some of our auto-dev code which caused this incompatibility. Thanks for reporting

**Comment by stackpoint** [comment]
Fixed here: https://github.com/stackpoint/anbennar_tweaks/commit/af8321d1f3ba7e007f76a4cca000d3f3cc4e348f
