### ISSUE TITLE
Dwarovar Claimer Wrongly Removed

### ISSUE THREAD

**Issue by Levedis** [stackpoint/anbennar_tweaks#6]
The Dwarovar Claimer Modifier for the Adventurers in the Serpentspine should only be removed wenn attacking someone outside the serpentspine.
However, according to 00_diplomatic_actions.txt/declarewar (line 272) it is instead removed if the target owns any province in the serpentspine. which is very contradicting.
i suggest replacing the
`FROM = { any_owned_province = { continent = serpentspine } }`
with
`FROM = { NOT = { any_owned_province = { continent = serpentspine } }`

that way it works the way its supposed to. (not sure how declaring war on someone who only has a subject in the serpentspine works, i guess the subjects provinces dont count as owned by FROM)

**Comment by stackpoint** [comment]
This was fixed about a month ago. (https://github.com/stackpoint/anbennar_tweaks/blob/main/common/diplomatic_actions/00_diplomatic_actions.txt#L275) What version of the mod are you running?

**Comment by Levedis** [comment]
I downloaded the version from the release page 2 days ago.

**Comment by stackpoint** [comment]
Ah the release version is outdated. You'll have to grab the latest files directly from the repo: https://github.com/stackpoint/anbennar_tweaks/archive/main.zip
![image](https://user-images.githubusercontent.com/5704491/111042410-56148e00-83e1-11eb-812b-e31c90457d29.png)

**Comment by stackpoint** [comment]
I released a new update [here](https://github.com/stackpoint/anbennar_tweaks/releases/tag/v3) but you will need to grab the files directly from the repo for the latest updates.
