### ISSUE TITLE
Localisation Missing: Hul-Jorkad ( I10 ) National Ideas

### ISSUE THREAD

**Issue by Levedis** [stackpoint/anbennar_tweaks#7]
See Title.
Corresponding File is [main: localisation/anb_powers_and_ideas_l_english.yml: 2480](https://github.com/stackpoint/anbennar_tweaks/blob/0dcd3cf9d5233d12ad6c86d6f5c5d54b7b7b6fa3/localisation/anb_powers_and_ideas_l_english.yml#L2480)

If it is intended i suggest placing a comment there to explain that.

**Comment by stackpoint** [comment]
WishPig let me know that the idea set is WIP. Will wait for the main repo to update.
